CREATE DATABASE CatalogDatabase;

CREATE TABLE item (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  publish_date DATE NOT NULL,
  archived BOOLEAN
);

CREATE TABLE games (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  multiplayer BOOLEAN,
  last_played_at DATE NOT NULL,
  item_id INT,
  FOREIGN KEY (item_id) REFERENCES item(id),
);

CREATE TABLE author (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  first_name VARCHAR (50),
  last_name VARCHAR (50),
)

CREATE TABLE music_album (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  item_id INT,
  on_spotify BOOLEAN NOT NULL,
  FOREIGN KEY(item_id) REFERENCES item(id)
)

CREATE TABLE genre (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
)

CREATE TABlE book (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  item_id INT,
  publisher VARCHAR(50)
  cover_state VARCHAR(50) NOT NULL,
  FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE label (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  color VARCHAR(50) NOT NULL
)